### ISSUE TITLE
Out with tag and commitish failing with 404 {message: 404 Tag Not Found}

### ISSUE THREAD

**Issue by petewall** [orange-cloudfoundry/gitlab-release-resource#1]
I'm trying to use this resource to create a release on a private GitLab repo and then attach some built binaries to it. The resource appears to check if the tag exists (which it doesn't), but this causes the put to fail instead of creating the tag based on the commit SHA.

Here's a snippet of my pipeline:
```yaml
---
resource_types:
  - name: gl-release
    type: registry-image
    source:
      repository: orangeopensource/gitlab-release-resource
      username: ((harbor.username))
      password: ((harbor.token))

resources:
  - name: source
    type: git
    source:
      uri: git@my.private.gitlab.companyname.com:myorganization/myproject.git
      private_key: ((gitlab.private_key))
      branch: main

  - name: release
    type: gl-release
    icon: gitlab
    source:
      repository: myorganization/myproject
      access_token: ((gitlab.access_token))
      gitlab_api_url: https://my.private.gitlab.companyname.com

  - name: version
    type: semver
    ...

jobs:
  - name: build
    plan:
      - get: source
      - get: version
      - task: build
          file: source/ci/tasks/build.yaml
      - put: release
        inputs: [build, source, version]
        params:
          commitish: source/.git/ref              # commit sha
          tag: version/version                        # 1.0.0
          globs:
            - build/*                                         # binaries
```

When this runs, I see this error:
```
error running command: GET https://my.private.gitlab.companyname.com/api/v4/projects/myorganization/myproject/repository/tags/1.0.0: 404 {message: 404 Tag Not Found}
```

Looking at the code, it seems that `GetTag()` is returning the error before the check for `http.StatusNotFound`, which means `ensureTag()` doesn't treat it as a case to use the `commitish` parameter.
