### ISSUE TITLE
Releases are not sorted correctly

### ISSUE THREAD

**Issue by winkingturtle-vmw** [orange-cloudfoundry/gitlab-release-resource#64]
We were trying to use this resource in our concourse but realized that the check resources are not fetched by the date the release was published. 

```yml
- name: apparmor
  type: gitlab-release
  source:
     respository: apparmor/apparmor
     tag_filter: v2.*
```
When using the above setup, `2.13.5` is fetched as latest instead of `2.13.11`. Do you have any recommendation on what we need to change for us to be able to use this resource?
